FormDonasi/urls.py
from django.urls import path
from .views import index

#url for app
urlpatterns = [
    path('', index, name='index'),
    path('submit/', index, name='donateSubmission')
]

KasusBencana/urls.py
from django.urls import re_path
from .views import index
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
]

ProgramDonasi/urls.py
from django.urls import re_path
from .views import index
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
]

Register/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib.auth.views import LogoutView
import oauth2_provider.views as oauth2_views
from django.conf import settings
from .views import *

urlpatterns = [
	path('login/', login_view, name="login_user"),
	path('signup/', register_view, name='register_user'),
    #re_path(r'^$', index, name='index'),
    # OAuth 2 endpoints:
    #path('', include('social_django.urls', namespace='social')),
    #url(r'^login/$', include('social_django.urls', namespace='social')),
    # url(r'^logout/$', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
]

tugas1e7/urls.py
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import re_path, path
from django.views.generic.base import RedirectView
from Register.views import *



urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', RedirectView.as_view(url='kasus-bencana/')),
    re_path(r'^kasus-bencana/', include(('KasusBencana.urls','ProgramDonasi'), namespace='KasusBencana')),
	re_path(r'^program-donasi/', include(('ProgramDonasi.urls','ProgramDonasi'), namespace='ProgramDonasi')),
	re_path(r'^form-donasi/', include(('FormDonasi.urls', 'FormDonasi'), namespace='FormDonasi')),
    path('account/', include(('Register.urls', 'account'), namespace='account')),
    path('auth/', include('social_django.urls', namespace='social')),
    url(r'^auth/logout/$',logout_view,  name='logout'),
]

FormDonasi/models.py
from django.db import models
from .choices import *

# Create your models here.



class IkutDonasi(models.Model):
	
	nama_program = models.CharField(max_length=80, choices=PROGRAM_DONASI)
	nama_donatur = models.CharField(max_length=32)
	email_donatur = models.EmailField(max_length=64)
	nominal = models.DecimalField(max_digits=16, decimal_places=10)

KasusBencana/models.py
from django.db import models

# Create your models here.

ProgramDonasi/models.py
from django.db import models

# Create your models here.

Register/models.py
from django.db import models

class UserAccount(models.Model):
 	username = models.CharField(max_length=64)
 	email = models.EmailField()
 	password = models.CharField(max_length=64)

FormDonasi/forms.py
from django import forms
from .models import IkutDonasi
from .choices import PROGRAM_DONASI

class FormDonasi(forms.Form):
	nama_program = forms.ChoiceField(
		initial='',
		label='',
		choices=PROGRAM_DONASI,
		required=True,
		widget=forms.Select(attrs={'placeholder':'Pilih program donasi'}))
	nama_donatur = forms.CharField(
		label='',
		widget=forms.TextInput(attrs={'placeholder':'Your name'}))
	email_donatur = forms.EmailField(
		label='',
		widget=forms.TextInput(attrs={'placeholder':'Your e-mail'}),
		required=True)
	nominal = forms.DecimalField(
		label='',
		widget=forms.NumberInput(attrs={'placeholder':'Your donation*'}),
		help_text="(<i>*in Rupiah, ex : 50000</i>)", required=True)
	#anonym = forms.BooleanField(
	#	initial=False,
	#	label='',
	#	required=False,
	#	help_text="Donate as an Anonymous")

Register/forms.py
from django import forms
from django.contrib.auth import (
	authenticate,
	get_user_model, 
	login, 
	logout,
	)

User = get_user_model()
fieldStyling = (
	'margin-left: auto;'
	+'margin-right: auto;'
	+'margin-top: 10px;'
	+'margin-bottom: 10px;'
	+'padding-left: 25px;'
	+'padding-right: 25px;'
	+'padding-top: 5px;'
	+'padding-top: 5px;'
	+'min-width: 260px;'
	+'justify-content: center;')

class UserLoginForm(forms.Form):

	email = forms.CharField(
		label='',
		required=True,
		widget=forms.EmailInput(attrs={
			'type' : 'email',
			'class' : 'form-control',
			'id' : 'loginEmailInp',
			'aria-describedby' : 'emailHelp',
			'placeholder' : 'Email',
			'style' : fieldStyling,
			})
		)
	password = forms.CharField(
		label='',
		required=True,
		widget=forms.PasswordInput(attrs={
			'type':"password", 
			'class' : "form-control", 
			'id':'loginPassInp',
			'aria-describedby' : 'emailHelp',
			'placeholder' : 'Password',
    		'style' : fieldStyling,
			})
		)

	def clean(self, *args, **kwargs):
		email = self.cleaned_data.get("email")
		password = self.cleaned_data.get("password")

		if email and password:
			user = authenticate(email=email, password=password)
			
			if not user:
				raise forms.ValidationError("This user doesn't exist!")
			
			if not password.check_password(password):
				raise forms.ValidationError("Incorrect password")
		return super(UserLoginForm, self).clean(*args, **kwargs)

class UserRegisterForm(forms.Form):
	email = forms.CharField()
	email_confirm =  forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)
	display_name = forms.CharField()

	def clean(self, *args, **kwargs):
		if email and email_confirm and password and display_name:
			if email != email_confirm : 
				raise forms.ValidationError("Email is not match with the confirmation Email")

			#if User.objects.get(email=email) not None:
        	#	raise forms.ValidationError('This email address is already in use.')
		return super(UserRegisterForm, self).clean(*args, **args)

FormDonasi/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import IkutDonasi
from .forms import FormDonasi

response = {}
		
def index(request):
  	if request.user.is_authenticated:
  		print(request.user)
  	response['retrieved_donations'] = IkutDonasi.objects.all()
  	response['title'] = 'Donation Submission'
  	response['get_donation_form'] = FormDonasi(request.POST or None)
  	if (request.method == 'POST'):
  		if (response['get_donation_form'].is_valid()):
  			response['nama_donatur'] = request.POST['nama_donatur']
  			response['nama_program'] = request.POST['nama_program']
  			response['email_donatur'] = request.POST['email_donatur']
  			response['nominal'] = request.POST['nominal']
  			ikut_donasi = IkutDonasi(nama_program=response['nama_program'],
						  			 nama_donatur=response['nama_donatur'],
						   			 email_donatur=response['email_donatur'],
						   			 nominal=response['nominal'])
  			ikut_donasi.save()
  	return render(request, 'FormDonasi.html', response)

# Create your views here.

KasusBencana/views.py
from django.shortcuts import render
def index(request):
    return render(request, 'KasusBencana.html')
# Create your views here.

ProgramDonasi/views.py
from django.shortcuts import render
def index(request):
    return render(request, 'base.html')
# Create your views here.

Register/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .forms import UserLoginForm, UserRegisterForm

response = {}
def login_view(request):
	response['login_form'] = UserLoginForm()
	if (request.method == 'POST'):
		email = request.POST['email']
		password = request.POST['password']
		response['user'] = authenticate(request, email=email, password=password)
		if response['user'] is not None:
			response['user'].save()
			HttpResponseRedirect("/kasus-bencana/")
		else:
			HttpResponse(status=403)
	else : 
		response['login_form'] = UserLoginForm()
	return render(request, "login_page.html", response)
	#return render(request, "login_page.html", response)

def register_view(request):
	context = {}
	form = UserRegisterForm(request.POST or None)
	if form.is_valid():
		new_account = UserRegisterModel(
			email = request.POST["email"],
			password = request.POST["password"],
			display_name = request.POST["display_name"],
			birthDate = request.POST["birthDate"],
		)
		new_account.save()
		return HttpResponseRedirect(nextState)
	else : 
		form = UserRegisterForm(request.POST or None)
	return render(request, "register_page.html", context)

def logout_view(request):
	logout(request)
	for key in request.session.keys():
		del request.session[key]
	return HttpResponseRedirect('/')

FormDonasi/templates/FormDonasi.html
{% extends "base.html" %}
{% block content %}
<div class="bg flex-vertical">
		<h1>Thank you for your donation!</h1>
		<h2>Now here is how to proceed:</h2>
		<div class="form-container">
			<form class="flex-vertical" id="form_donasi" method="POST" action="{% url 'FormDonasi:index' %}">

				{% csrf_token %}
				
				{{ get_donation_form.as_p }}

				<button class="main form-button" type="submit" value=submit">Submit</button>

			</form>
		</div>
</div>
{% endblock %}

FormDonasi/templates/donasi.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}

KasusBencana/templates/KasusBencana.html
{% extends "base.html" %}
{% block content %}
    <div class="bg flex-vertical">
        <div class="flex-horizontal">
            <section class="flex-vertical">
                <div class="img-holder">
                    <img class="vertical" src="placeholder.png">
                </div>
                <h3>Bantuan korban Bencana Palu</h3>
                <p>PT. Wilmar Nabati Indonesia (WNI) mengirim bantuan sembilan bahan pokok (sembako) seberat 18 ton atau senilai Rp 3 miliar untuk korban bencana gempa dan tsunami di Palu, Sigi, dan Donggala, Jumat (19/10). Bantuan itu dilepas Direktur PT. WNI Erik Tjiah, dan Direktur PT. Wilmar Nabati Gresik, Saronto beserta jajaran direksi di perusahaan setempat.

Erik Tjiah menyatakan, bahwa bantuan 18 ton sembako itu berupa beras, minyak goreng dan kebutuhan lain. "Pengiriman bantuan...
                </p>
                <button class="main">Read More</button>
            </section>
            <section class="flex-vertical">
                <div class="img-holder">
                    <img class="horizontal" src="placeholder.png">
                </div>
                <h3>Train Disaster</h3>
                <p>Angry relatives staged a protest Saturday on the tracks where a speeding train ploughed into crowds watching fireworks, killing about 60 people in the latest disaster to bedevil India’s railway network.

The Jalandhar-Amritsar express hit scores of people who had gathered on the tracks Friday to get a view of a firework-packed effigy of the demon king Ravana for a Hindu festival.

Many of the victims were dismembered beyond recognition and police said it would take several days to complete the identification...

                </p>
                <button class="main">Read More</button>
            </section>
            <aside>
                <div class="img-holder mini">
                    <img class="horizontal" src="placeholder.png">
                </div>
                <h5>Arizona hurricane disaster</h5>
                <p class="side">A major earthquake that displaces a mass population of people. Widespread power outages that cascade through a metro area. Catastrophic droughts or devastating floods that strand people in their homes.  

Natural disasters are an increasingly common reality for hundreds of thousands of Americans, and as climate change and urbanization...
                </p>
                <div class="img-holder mini">
                    <img class="horizontal" src="placeholder.png">
                </div>
                <h5>Wildfire in north America</h5>
                <p class="side">What if fixing fire really means fixing ourselves, fixing our relationships with each other, and the relationship we basically have with the earth?”

That was the question Toddi Steelman asked a roomful of concerned Bow Valley residents gathered in September to hear about what a future that combines wildfire and climate ...
                </p>
                <button class="main">Click here for more events</button>
            </aside>
        </div>
    </div>
{% endblock %}

ProgramDonasi/templates/ProgramDonasi.html
{% extends "base.html" %}
{% block content %}
<h1>this is page program donasi</h1>
{% endblock %}

Register/templates/Register.html
{% extends "base.html" %}
{% block content %}
<div class="bg flex-vertical">
    <h1>This is the h1 example.</h1>
    <h2>This is the h2 example.</h2>
	<form>
		<div class="form-container">
			<form class="flex-vertical">
                <input type="text">
                <input type="text">
                <input type="text">
                <input type="text">
				<input type="checkbox" name="agreement">By checking this box, you agree to our Terms and Conditions and Privacy Policy. <br>
                <button class="main form-button" type="submit">Submit</button>
            </form>
        </div>
	</form>
</div>
{% endblock %}

Register/templates/login_page.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang = "en">
	<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <meta name="google-signin-client_id" content="526386525514-o7f8g5qdfhl9r060sogc57jjo14n1csc.apps.googleusercontent.com">

        <title>Login - SinarPerak</title>

        <!-- Bootstrap Core CSS-->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <!-- Custom CSS and font here-->
        <link href="{% static 'styles/default.css' %}" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600i,800,900" rel="stylesheet" type="text/css">
        <script src="https://apis.google.com/js/platform.js" async defer></script>

    </head>

    <body>
    	<nav class="navbar navbar-light bg-light">
			<a class="navbar-brand" href="#">
			    <div class="row">
			    	<div class="col-sm"></div>
				    <div class="col-sm">
				    	<h2 style="
				    		font-size: 24px;
				    		text-align: center;
				    		margin-left: auto;
				    		margin-right: auto;">SinarPerak
						</h2>
				    </div>
			    <div class="col-sm"></div>
			    </div>
			</a>
		</nav>
    	<div class="container-fluid">
    		<div class="row"
			    style="
			    margin-top: 1.5vw">
			    <div class="col-sm">
			    </div>
			    <div class="col-sm">
			    	<div class="row justify-content-md-center">
			    		<a class="btn btn-primary" href="{% url 'social:begin' 'google-oauth2' %}"
			    		style="
			
			    			margin-left: auto;
			    			margin-right: auto;
			    			margin-top: 25px;
			    			margin-bottom: 25px;
			    			border-left-width: 2.5rem;
			    			border-right-width: 2.5rem;
			    			padding-left: 25px;
			    			padding-right: 25px;
			    			padding-top: 5px;
			    			padding-top: 5px;
			    		"
			    		>Sign in with Google</a>
			    		
			    	</div>
			    	<div class="row justify-content-md-center">
			    		<div class="line2" 
			    		style="
			    			min-width: 122px;
			    			width: 11.7vw;
							height: 0px;
							top: 707px;
							border: 1px solid #000000;
							margin-top: 15px;
							margin-bottom: 15px;
							margin-left: auto;
							"
						>	
						</div>

						<h5 style="
						font-size: 18px;
						margin: 10px;
						text-align: center;">
						or
						</h5>

			    		<div class="line2" 
			    		style="
			    			min-width: 122px;
			    			width: 11.7vw;
							height: 0px;
							top: 707px;
							border: 1px solid #000000;
							margin-top: 15px;
							margin-bottom: 15px;
							margin-right: auto;
							"
						>	
						</div>
			    	</div>
			    	
			    	
			    	<div class="row justify-content-md-center">
			    		<h4 class="text 1 bold"
			    		style="
			    			margin-left: auto;
							margin-right: auto;
							margin-top: 25px;
							margin-bottom: 20px;
							font-size: 22px;
							text-align: center;
							"> Sign In With Your Email
			    		</h4>
			    	</div>
			    	
			    	<!----------------- LOGIN FORM START ------------------->

			    	<form id='loginform' method="POST" action="
			    	{% url 'account:login_user' %}">

				    	<div class="row justify-content-md-center">

				    		{% csrf_token %}

				    		{{ login_form.as_p }}
				    		
				    	
				    	</div>
				    	<div class="row justify-content-md-center">
				    		<button type="submit" class="btn btn-success"
				    		style="
				    			margin-left: auto;
				    			margin-right: auto;
				    			margin-top: 25px;
				    			margin-bottom: 25px;
				    			border-left-width: 2.5rem;
				    			border-right-width: 2.5rem;
				    			padding-left: 25px;
				    			padding-right: 25px;
				    			padding-top: 5px;
				    			padding-top: 5px;
				    		"
				    		>Sign In</button>
			    		</div>
			    	</form>
	    	
			    	

			    	<!--------------- END OF LOGIN FORM ------------------->
			    	
			    	<div class="row justify-content-md-center">
			    		<div class="line3" 
			    		style="
			    			min-width: 280px;
			    			width: 26vw;
							height: 0px;
							left: 100px;
							right: 100px;
							top: 707px;
							border: 1px solid #000000;
							margin-top: 15px;
							margin-bottom: 15px;
							margin-left: auto;
							margin-right: auto;
							"
						>	
						</div>
			    	</div>
			    	
			    	<div class="row justify-content-md-center">
			    		<p
			    		style="
			    		margin-top: 25px;
			    		margin-bottom: 15px;
			    		justify-content: center;
			    		margin-left: auto;
						margin-right: auto;
						text-align: center;
			    		">Don't have an account?</p>
			    	</div>
			    	
			    	<div class="row justify-content-md-center">
			    		<button type="button" id="btn_loginToRegister" class="btn btn-warning"
			    		href="account/register"
			    		style="
			    			margin-left: auto;
			    			margin-right: auto;
			    			margin-top: 5px;
			    			margin-bottom: 15px;
			    			border-left-width: 5.5rem;
			    			border-right-width: 5.5rem;
			    			padding-left: 25px;
			    			padding-right: 25px;
			    			padding-top: 5px;
			    			padding-top: 5px;
			    			justify-content: center;
			    		">Sign Up</button>
			    	</div>
			    	<script>
						document.getElementById("btn_loginToRegister").addEventListener("click", function(){
    							window.location.replace("/account/signup");
								}
							);
					</script>
			    </div>
			    <div class="col-sm justify-content-md-center">
			    	
			    </div>
			</div>
		</div>
    </body>
</html>
	
	

Register/templates/register_page.html
<!DOCTYPE html>
<html lang = "en">
	<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <meta name="google-signin-client_id" content="526386525514-o7f8g5qdfhl9r060sogc57jjo14n1csc.apps.googleusercontent.com">

        <title>Sign Up - SinarPerak</title>

        <!-- Bootstrap Core CSS-->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <!-- Custom CSS and font here-->
        <!--<link href=" static 'styles/default.css' " rel="stylesheet">-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600i,800,900" rel="stylesheet" type="text/css">
        <script src="https://apis.google.com/js/platform.js" async defer></script>

    </head>

    <body>
    	<nav class="navbar navbar-light bg-light">
			<a class="navbar-brand" href="#">
			    <div class="row">
			    	<div class="col-sm"></div>
				    <div class="col-sm">
				    	<h2 style="
				    		font-size: 24px;
				    		text-align: center;
				    		margin-left: auto;
				    		margin-right: auto;">SinarPerak
						</h2>
				    </div>
			    <div class="col-sm"></div>
			    </div>
			</a>
		</nav>
    	<div class="container-fluid">
    		<div class="row"
			    style="
			    margin-top: 1.5vw">
			    <div class="col-sm">
			    </div>
			    <div class="col-sm">
			    	<div class="row justify-content-md-center">
			    		<a class="btn btn-primary" href="{% url 'social:begin' 'google-oauth2' %}"
			    		style="
			    			margin-left: auto;
			    			margin-right: auto;
			    			margin-top: 15px;
			    			margin-bottom: 15px;
			    			border-left-width: 2.5rem;
			    			border-right-width: 2.5rem;
			    			padding-left: 25px;
			    			padding-right: 25px;
			    			padding-top: 5px;
			    			padding-top: 5px;
			    		"
			    		>Sign up with Google</a>
			    		
			    	</div>
			    	<div class="row justify-content-md-center">
			    		<div class="line2" 
			    		style="
			    			min-width: 122px;
			    			width: 11.7vw;
							height: 0px;
							top: 707px;
							border: 1px solid #000000;
							margin-top: 15px;
							margin-bottom: 15px;
							margin-left: auto;
							"
						>	
						</div>

						<h5 style="
						font-size: 18px;
						margin: 10px;
						text-align: center;">
						or
						</h5>

			    		<div class="line2" 
			    		style="
			    			min-width: 122px;
			    			width: 11.7vw;
							height: 0px;
							top: 707px;
							border: 1px solid #000000;
							margin-top: 15px;
							margin-bottom: 15px;
							margin-right: auto;
							"
						>	
						</div>
			    	</div>
			    	
			    	
			    	<div class="row justify-content-md-center">
			    		<h4 class="text 1 bold"
			    		style="
			    			margin-left: auto;
							margin-right: auto;
							margin-top: 15px;
							margin-bottom: 10px;
							font-size: 22px;
							text-align: center;
							"> Sign Up With Your Email
			    		</h4>
			    	</div>
			    	
			    	<div class="row justify-content-md-center">
			    		<input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Email"
			    		style="
			    			margin-left: 3.5rem;
			    			margin-right: 3.5rem;
			    			margin-top: 10px;
			    			margin-bottom: 10px;
			    			padding-left: 25px;
			    			padding-right: 25px;
			    			padding-top: 5px;
			    			padding-top: 5px;
			    			min-width: 260px;
			    		">
			    	</div>

			    	<div class="row justify-content-md-center">
			    		<input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Email Confirmation"
			    		style="
			    			margin-left: 3.5rem;
			    			margin-right: 3.5rem;
			    			margin-top: 10px;
			    			margin-bottom: 10px;
			    			padding-left: 25px;
			    			padding-right: 25px;
			    			padding-top: 5px;
			    			padding-top: 5px;
			    			min-width: 260px;
			    		">
			    	</div>

			    	<div class="row justify-content-md-center">
			    		<input type="password" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Password" 
			    		style="
			    			margin-left: 3.5rem;
			    			margin-right: 3.5rem;
			    			margin-top: 10px;
			    			margin-bottom: 10px;
			    			padding-left: 25px;
			    			padding-right: 25px;
			    			padding-top: 5px;
			    			padding-top: 5px;
			    			min-width: 260px;
			    			justify-content: center;
			    		"
			    		>
			    	</div>

			    	<div class="row justify-content-md-center">
			    		<input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Your Name"
			    		style="
			    			margin-left: 3.5rem;
			    			margin-right: 3.5rem;
			    			margin-top: 10px;
			    			margin-bottom: 10px;
			    			padding-left: 25px;
			    			padding-right: 25px;
			    			padding-top: 5px;
			    			padding-top: 5px;
			    			min-width: 260px;
			    		">
			    	</div>
			    	
			    	<div class="row justify-content-md-center">
			    		<button type="button" class="btn btn-success"
			    		style="
			    			margin-left: auto;
			    			margin-right: auto;
			    			margin-top: 15px;
			    			margin-bottom: 15px;
			    			border-left-width: 2.5rem;
			    			border-right-width: 2.5rem;
			    			padding-left: 25px;
			    			padding-right: 25px;
			    			padding-top: 5px;
			    			padding-top: 5px;
			    		"
			    		>Sign Up</button>
			    	</div>
			    	
			    	<div class="row justify-content-md-center">
			    		<div class="line3" 
			    		style="
			    			min-width: 280px;
			    			width: 26vw;
							height: 0px;
							left: 100px;
							right: 100px;
							top: 707px;
							border: 1px solid #000000;
							margin-top: 15px;
							margin-bottom: 15px;
							margin-left: auto;
							margin-right: auto;
							"
						>	
						</div>
			    	</div>
			    	
			    	<div class="row justify-content-md-center">
			    		<p
			    		style="
			    		margin-top: 15px;
			    		margin-bottom: 15px;
			    		justify-content: center;
			    		margin-left: auto;
						margin-right: auto;
						text-align: center;
			    		">Already have an account? 
			    		<a href="/account/login" ><b>Sign In</b></a></p>
			    	</div>
			    </div>
			    <div class="col-sm justify-content-md-center">
			    	
			    </div>
			</div>
		</div>
    </body>
</html>
	
	

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang = "en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <meta name="google-signin-client_id" content="526386525514-o7f8g5qdfhl9r060sogc57jjo14n1csc.apps.googleusercontent.com">

        <!-- Bootstrap Core CSS-->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <!-- Custom CSS and font here-->
        <link href={% static 'styles/default.css' %} rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600i,800,900" rel="stylesheet" type="text/css">
        <script src="https://apis.google.com/js/platform.js" async defer></script>

    </head>

    <!--         NAVIGATION BAR SECTION               -->
	<body>
		<header>
			<h4 id="log222">SINAR PERAK FOUNDATION</h4>
            {% if user.is_authenticated %}
                <p>Hello, {{ user.first_name }}<p/>
                <button class="head"><a class="nav-textxx" href="/kasus-bencana/">Events</a> <br/></button>
                <button class="head"><a class="nav-textxx" href="/program-donasi/">Fundings</a> <br/></button>
			    <button class="head"><a class="nav-textxx" href="/form-donasi/">Donate!</a> <br/></button>
                <a class="btn btn-danger" href="/auth/logout/">Sign Out</a> <br/>
            {% else %}
                <a class="btn btn-primary" href="/account/login" style="
                margin-right: 1.5rem">Sign In</a>
            {% endif %}
			
		</header>
    {% block content %}
    {% endblock %}


    <!-- Bootstrap Core JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <!-- Custom Script -->
    <script src="{% static 'js/interactive.min.js' %}"}></script>
    <script>
        $(function() {
            $( "#id_date" ).datepicker({
                minDate: 0,
                maxDate: "+24M",
                yearRange: "1900:2025",
                // You can put more options here.
            });
        });
    </script>
    </body>
</html>

<!--#########################OLD HTML BELOW#################-->